/*Problem 2
Even Fibonacci numbers
   
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let result=0;
for (let fp=1,fn=1,f=0; f<4000000;f=fp+fn) {
  console.log(f);
  if (f%2===0){
    result+=f;
    console.log(`result: ${result}`);
  }
  fp=fn;
  fn=f;
}
console.log(`final result: ${result}`);

//answer: 4613732
